In [1]:
import pandas as pd

In [2]:
#datacollection
dataset=pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
#preprocessing categorical data
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [5]:
#spliting input and output data
input_data=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
output_data=dataset[['Profit']]
print(input_data)
print(output_data)

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0
       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [6]:
#spliting training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
7   130298.13       145530.06        323876.68              1               0
14  119943.24       156547.42        256512.92              1               0
45    1000.23       124153.04          1903.93              0               1
48     542.05        51743.15             0.00              0               1
29   65605.48       153032.06        107138.38              0               1
15  114523.61       122616.84        261776.23              0               1
30   61994.48       115641.28         91131.24              1               0
32   63408.86       129219.61         46085.25              0               0
16   78013.11       121597.55        264346.06              0               0
42   23640.93        96189.63        148001.11              0               0
20   76253.86       113867.30        298664.47              0               0
43   15505.73       127382.30         35534.17              0               1
8   120542.52       148718.95        311613.29              0               1
13   91992.39       135495.07        252664.93              0               0
25   64664.71       139553.16        137962.62              0               0
5   131876.90        99814.71        362861.36              0               1
17   94657.16       145077.58        282574.31              0               1
40   28754.33       118546.05        172795.67              0               0
49       0.00       116983.80         45173.06              0               0
1   162597.70       151377.59        443898.53              0               0
12   93863.75       127320.38        249839.44              1               0
37   44069.95        51283.14        197029.42              0               0
24   77044.01        99281.34        140574.81              0               1
6   134615.46       147198.87        127716.82              0               0
23   67532.53       105751.03        304768.73              1               0
36   28663.76       127056.21        201126.82              1               0
21   78389.47       153773.43        299737.29              0               1
19   86419.70       153514.11             0.00              0               1
9   123334.88       108679.17        304981.62              0               0
39   38558.51        82982.09        174999.30              0               0
46    1315.46       115816.21        297114.46              1               0
3   144372.41       118671.85        383199.62              0               1
0   165349.20       136897.80        471784.10              0               1
47       0.00       135426.92             0.00              0               0
44   22177.74       154806.14         28334.72              0               0
       Profit
7   155752.60
14  132602.65
45   64926.08
48   35673.41
29  101004.64
15  129917.04
30   99937.59
32   97427.84
16  126992.93
42   71498.49
20  118474.03
43   69758.98
8   152211.77
13  134307.35
25  107404.34
5   156991.12
17  125370.37
40   78239.91
49   14681.40
1   191792.06
12  141585.52
37   89949.14
24  108552.04
6   156122.51
23  108733.99
36   90708.19
21  111313.02
19  122776.86
9   149759.96
39   81005.76
46   49490.75
3   182901.99
0   192261.83
47   42559.73
44   65200.33
    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
28   66051.52       182645.56        118148.20              1               0
11  100671.96        91790.61        249744.55              0               0
10  101913.08       110594.11        229160.95              1               0
41   27892.92        84710.77        164470.71              1               0
2   153441.51       101145.55        407934.54              1               0
27   72107.60       127864.55        353183.81              0               1
38   20229.59        65947.93        185265.10              0               1
31   61136.38       152701.92         88218.23              0               1
22   73994.56       122782.75        303319.26              1               0
4   142107.34        91391.77        366168.42              1               0
33   55493.95       103057.49        214634.81              1               0
35   46014.02        85047.44        205517.64              0               1
26   75328.87       144135.98        134050.07              1               0
34   46426.07       157693.92        210797.67              0               0
18   91749.16       114175.79        294919.57              1               0
       Profit
28  103282.38
11  144259.40
10  146121.95
41   77798.83
2   191050.39
27  105008.31
38   81229.06
31   97483.56
22  110352.25
4   166187.94
33   96778.92
35   96479.51
26  105733.54
34   96712.80
18  124266.90

In [7]:
#standardizing the input values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)

[[ 1.17644103  0.84515251  0.94354978  2.         -0.76870611]
 [ 0.96420324  1.27283565  0.42738817  2.         -0.76870611]
 [-1.47369826  0.0153175  -1.52350329 -0.5         1.30088727]
 [-1.48308929 -2.79556363 -1.53809178 -0.5         1.30088727]
 [-0.14952431  1.13637282 -0.71716495 -0.5         1.30088727]
 [ 0.85312042 -0.04431628  0.46771725 -0.5         1.30088727]
 [-0.22353674 -0.3151007  -0.83981652  2.         -0.76870611]
 [-0.19454707  0.21199679 -1.18497259 -0.5        -0.76870611]
 [ 0.10478723 -0.08388412  0.48740807 -0.5        -0.76870611]
 [-1.0096458  -1.07019473 -0.4040623  -0.5        -0.76870611]
 [ 0.06872897 -0.38396487  0.75036616 -0.5        -0.76870611]
 [-1.17638797  0.14067421 -1.26581817 -0.5         1.30088727]
 [ 0.97648631  0.9689421   0.84958395 -0.5         1.30088727]
 [ 0.39131191  0.45560401  0.3979037  -0.5        -0.76870611]
 [-0.16880669  0.6131351  -0.48098026 -0.5        -0.76870611]
 [ 1.2088001  -0.92947267  1.24226224 -0.5         1.30088727]
 [ 0.44593006  0.82758768  0.62707846 -0.5         1.30088727]
 [-0.90483959 -0.20234037 -0.21407884 -0.5        -0.76870611]
 [-1.49419935 -0.26298539 -1.19196207 -0.5        -0.76870611]
 [ 1.83846539  1.07214791  1.86319367 -0.5        -0.76870611]
 [ 0.42966802  0.13827054  0.37625394  2.         -0.76870611]
 [-0.59092478 -2.81342077 -0.02839248 -0.5        -0.76870611]
 [ 0.08492419 -0.95017758 -0.46096486 -0.5         1.30088727]
 [ 1.26493068  0.90993408 -0.55948669 -0.5        -0.76870611]
 [-0.11002675 -0.69903054  0.79713886  2.         -0.76870611]
 [-0.90669595  0.12801572  0.00300304  2.         -0.76870611]
 [ 0.11250125  1.16515207  0.75858643 -0.5         1.30088727]
 [ 0.27709192  1.15508553 -1.53809178 -0.5         1.30088727]
 [ 1.03371959 -0.585363    0.79877008 -0.5        -0.76870611]
 [-0.70388936 -1.58289852 -0.19719396 -0.5        -0.76870611]
 [-1.46723718 -0.30831009  0.73848951  2.         -0.76870611]
 [ 1.46491286 -0.19745694  1.39810017 -0.5         1.30088727]
 [ 1.89486118  0.51005662  2.07686138 -0.5         1.30088727]
 [-1.49419935  0.4529585  -1.53809178 -0.5        -0.76870611]
 [-1.0396359   1.20524087 -1.32098255 -0.5        -0.76870611]]
[[-0.1403821   2.28593993 -0.63280437  2.         -0.76870611]
 [ 0.5692117  -1.24096039  0.37552686 -0.5        -0.76870611]
 [ 0.59465017 -0.51102691  0.21780907  2.         -0.76870611]
 [-0.92249538 -1.51579286 -0.27786722  2.         -0.76870611]
 [ 1.65079661 -0.87781077  1.58762665  2.         -0.76870611]
 [-0.01625436  0.15939469  1.16810991 -0.5         1.30088727]
 [-1.07956593 -2.24414796 -0.11853428 -0.5         1.30088727]
 [-0.24112469  1.1235571  -0.86213689 -0.5         1.30088727]
 [ 0.02242149 -0.03787582  0.78603258  2.         -0.76870611]
 [ 1.41848712 -1.25644297  1.26760194  2.         -0.76870611]
 [-0.3567741  -0.80359112  0.10650537  2.         -0.76870611]
 [-0.55107837 -1.50272366  0.03664684 -0.5         1.30088727]
 [ 0.04977002  0.79103569 -0.5109594   2.         -0.76870611]
 [-0.54263284  1.31734166  0.07710403 -0.5        -0.76870611]
 [ 0.38632657 -0.37198959  0.7216716   2.         -0.76870611]]

In [10]:
#Gridsearch process started
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
regressor_grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
regressor_grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [13]:
re=regressor_grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.115114,0.077026,0.005829,0.001729,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.034050,-0.000735,-0.021177,0.000243,0.000650,-0.011014,0.014159,39
1,0.116258,0.047266,0.009784,0.001160,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",-0.031232,-0.000146,-0.019526,0.001639,0.001728,-0.009507,0.013494,38
2,0.047505,0.022440,0.006678,0.003401,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.031404,0.001661,-0.019270,0.001939,0.002249,-0.008965,0.013909,35
3,0.058858,0.038991,0.015473,0.013572,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.013716,0.021071,-0.005020,0.012813,0.014737,0.005977,0.013115,31
4,0.029645,0.021162,0.026875,0.016570,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.034108,-0.000682,-0.021162,0.000239,0.000633,-0.011016,0.014180,40
5,0.029383,0.012028,0.011805,0.010844,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.030005,-0.000781,-0.019755,0.001703,0.002016,-0.009364,0.013112,37
6,0.078859,0.038562,0.025321,0.017190,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.031167,0.001330,-0.019332,0.001957,0.002330,-0.008977,0.013808,36
7,0.101871,0.089059,0.010123,0.011667,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.013716,0.021071,-0.005020,0.012813,0.014737,0.005977,0.013115,31
8,0.073075,0.052432,0.005023,0.001039,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.026499,0.014759,-0.012628,0.004869,0.009013,-0.002097,0.015248,33
9,0.122590,0.019717,0.009720,0.011026,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.001359,0.020540,0.003701,0.018608,0.019700,0.012782,0.008425,30
10,0.030833,0.018485,0.011955,0.008201,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.000357,0.038149,0.005981,0.021525,0.024831,0.018026,0.013759,27
11,0.141653,0.019188,0.003586,0.000901,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.168299,0.196330,0.127171,0.118437,0.136477,0.149343,0.028911,23
12,0.028222,0.024850,0.003399,0.000723,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.027074,0.015285,-0.012483,0.004824,0.008842,-0.002121,0.015501,34
13,0.070041,0.046994,0.013140,0.010257,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.013349,0.014300,0.001451,0.019225,0.022544,0.014174,0.007185,29
14,0.037090,0.021262,0.006981,0.003054,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.001964,0.034972,0.005383,0.021696,0.025630,0.017929,0.012460,28
15,0.017441,0.008206,0.006352,0.002916,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.168299,0.196330,0.127171,0.118437,0.136477,0.149343,0.028911,23
16,0.017412,0.007084,0.002885,0.000396,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.044922,0.154578,0.066248,0.046247,0.085277,0.079454,0.040366,25
17,0.064335,0.041629,0.005614,0.002976,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.312620,0.200262,0.209181,0.161388,0.177585,0.212207,0.052945,20
18,0.075428,0.028356,0.003685,0.001310,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.269900,0.329480,0.210794,0.182555,0.223206,0.243187,0.051546,15
19,0.018651,0.008132,0.003071,0.000535,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.885216,0.867465,0.749197,0.421170,0.740816,0.732773,0.166621,5
20,0.041714,0.042224,0.012442,0.008664,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.039405,0.157814,0.067459,0.045834,0.083781,0.078859,0.042510,26
21,0.055507,0.033107,0.019109,0.007924,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.406877,0.151058,0.191000,0.165724,0.201115,0.223155,0.093563,18
22,0.046955,0.020249,0.006742,0.003125,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.285400,0.305140,0.206341,0.183691,0.229915,0.242098,0.046233,16
23,0.016563,0.011364,0.009478,0.010967,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.885216,0.867465,0.749197,0.421170,0.740816,0.732773,0.166621,5
24,0.033428,0.025101,0.018983,0.020153,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.103783,0.274256,0.139916,0.081810,0.158115,0.151576,0.066904,21
25,0.026662,0.013218,0.018606,0.019932,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.565505,0.341716,0.389590,0.227190,0.322058,0.369212,0.111442,14
26,0.045911,0.041265,0.019194,0.020895,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.489768,0.591270,0.417079,0.288056,0.415180,0.440271,0.099587,11
27,0.042662,0.035377,0.003853,0.001231,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.934048,0.964088,0.851435,0.512818,0.823348,0.817147,0.160678,3
28,0.045354,0.047082,0.003630,0.001175,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.093084,0.282675,0.141994,0.081069,0.154972,0.150759,0.071665,22
29,0.042113,0.033067,0.004938,0.003849,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.665490,0.272320,0.365312,0.227388,0.357444,0.377591,0.153026,13
30,0.059750,0.053613,0.005870,0.004083,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.513085,0.554404,0.408668,0.291031,0.426517,0.438741,0.091408,12
31,0.037861,0.028079,0.003331,0.000983,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.934048,0.964088,0.851435,0.512818,0.823348,0.817147,0.160678,3
32,0.026153,0.020182,0.003555,0.000823,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.157233,0.394690,0.210422,0.124586,0.229727,0.223331,0.093478,17
33,0.023854,0.016200,0.006809,0.005021,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.707439,0.444756,0.490467,0.199577,0.438689,0.456186,0.161610,10
34,0.006541,0.004841,0.002894,0.000576,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.637296,0.731395,0.552491,0.433562,0.568999,0.584749,0.098400,7
35,0.039251,0.034472,0.007581,0.008255,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.923897,0.955665,0.882735,0.639744,0.904589,0.861326,0.113352,1
36,0.021956,0.008104,0.016310,0.011064,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.141710,0.406151,0.213742,0.123719,0.225282,0.222121,0.100096,19
37,0.055020,0.037937,0.003992,0.001408,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.800444,0.363079,0.465192,0.182703,0.482206,0.458725,0.201346,9
38,0.058449,0.035291,0.005066,0.004298,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.663748,0.703801,0.542752,0.435207,0.574073,0.583916,0.094500,8
39,0.027693,0.015644,0.005704,0.003460,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.923897,0.955665,0.882735,0.639744,0.904589,0.861326,0.113352,1

In [15]:
print('The best model is ',regressor_grid.best_params_)

The best model is  {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}

In [16]:
print('The R_Score value for best parameter{}'.format(regressor_grid.best_params_))

The R_Score value for best parameter{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}

In [17]:
future_prediction=regressor_grid.predict([[12345,5334,654,0,1]])
print(future_prediction)

[4.12518451e+08]