In [1]:
import pandas as pd

In [2]:
#datacollection
dataset=pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
#datapreprocessing
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [5]:
#split input and output data
input_data=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
output_data=dataset[['Profit']]
print(input_data)
print(output_data)

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0
       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [6]:
#split train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
7   130298.13       145530.06        323876.68              1               0
14  119943.24       156547.42        256512.92              1               0
45    1000.23       124153.04          1903.93              0               1
48     542.05        51743.15             0.00              0               1
29   65605.48       153032.06        107138.38              0               1
15  114523.61       122616.84        261776.23              0               1
30   61994.48       115641.28         91131.24              1               0
32   63408.86       129219.61         46085.25              0               0
16   78013.11       121597.55        264346.06              0               0
42   23640.93        96189.63        148001.11              0               0
20   76253.86       113867.30        298664.47              0               0
43   15505.73       127382.30         35534.17              0               1
8   120542.52       148718.95        311613.29              0               1
13   91992.39       135495.07        252664.93              0               0
25   64664.71       139553.16        137962.62              0               0
5   131876.90        99814.71        362861.36              0               1
17   94657.16       145077.58        282574.31              0               1
40   28754.33       118546.05        172795.67              0               0
49       0.00       116983.80         45173.06              0               0
1   162597.70       151377.59        443898.53              0               0
12   93863.75       127320.38        249839.44              1               0
37   44069.95        51283.14        197029.42              0               0
24   77044.01        99281.34        140574.81              0               1
6   134615.46       147198.87        127716.82              0               0
23   67532.53       105751.03        304768.73              1               0
36   28663.76       127056.21        201126.82              1               0
21   78389.47       153773.43        299737.29              0               1
19   86419.70       153514.11             0.00              0               1
9   123334.88       108679.17        304981.62              0               0
39   38558.51        82982.09        174999.30              0               0
46    1315.46       115816.21        297114.46              1               0
3   144372.41       118671.85        383199.62              0               1
0   165349.20       136897.80        471784.10              0               1
47       0.00       135426.92             0.00              0               0
44   22177.74       154806.14         28334.72              0               0
       Profit
7   155752.60
14  132602.65
45   64926.08
48   35673.41
29  101004.64
15  129917.04
30   99937.59
32   97427.84
16  126992.93
42   71498.49
20  118474.03
43   69758.98
8   152211.77
13  134307.35
25  107404.34
5   156991.12
17  125370.37
40   78239.91
49   14681.40
1   191792.06
12  141585.52
37   89949.14
24  108552.04
6   156122.51
23  108733.99
36   90708.19
21  111313.02
19  122776.86
9   149759.96
39   81005.76
46   49490.75
3   182901.99
0   192261.83
47   42559.73
44   65200.33
    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
28   66051.52       182645.56        118148.20              1               0
11  100671.96        91790.61        249744.55              0               0
10  101913.08       110594.11        229160.95              1               0
41   27892.92        84710.77        164470.71              1               0
2   153441.51       101145.55        407934.54              1               0
27   72107.60       127864.55        353183.81              0               1
38   20229.59        65947.93        185265.10              0               1
31   61136.38       152701.92         88218.23              0               1
22   73994.56       122782.75        303319.26              1               0
4   142107.34        91391.77        366168.42              1               0
33   55493.95       103057.49        214634.81              1               0
35   46014.02        85047.44        205517.64              0               1
26   75328.87       144135.98        134050.07              1               0
34   46426.07       157693.92        210797.67              0               0
18   91749.16       114175.79        294919.57              1               0
       Profit
28  103282.38
11  144259.40
10  146121.95
41   77798.83
2   191050.39
27  105008.31
38   81229.06
31   97483.56
22  110352.25
4   166187.94
33   96778.92
35   96479.51
26  105733.54
34   96712.80
18  124266.90

In [11]:
#module creation and Grid search
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
paramgrid={'criterion':['squared_error','absolute_error','poisson'],'splitter':['best','random']}
regressor_grid=GridSearchCV(DecisionTreeRegressor(),paramgrid,refit=True,verbose=3,n_jobs=-1)
regressor_grid.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [12]:
result=regressor_grid.cv_results_
result

{'mean_fit_time': array([0.01512184, 0.01457572, 0.00792236, 0.0064477 , 0.00569811,
        0.00583029]),
 'std_fit_time': array([0.00928081, 0.01004318, 0.00463034, 0.00146388, 0.00116525,
        0.00100811]),
 'mean_score_time': array([0.01609092, 0.01119428, 0.0078764 , 0.00546474, 0.00516272,
        0.00363874]),
 'std_score_time': array([0.00514963, 0.0031691 , 0.00463115, 0.00152714, 0.00063382,
        0.00018776]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'absolute_error',
                    'absolute_error', 'poisson', 'poisson'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'criterion': 'squared_error', 'splitter': 'best'},
  {'criterion': 'squared_error', 'splitter': 'random'},
  {'criterion': 'absolute_error', 'splitter': 'best'},
  {'criterion': 'absolute_error', 'splitter': 'random'},
  {'criterion': 'poisson', 'splitter': 'best'},
  {'criterion': 'poisson', 'splitter': 'random'}],
 'split0_test_score': array([0.83235844, 0.89873075, 0.85741228, 0.83587976, 0.84463342,
        0.86841688]),
 'split1_test_score': array([0.76500246, 0.54512957, 0.84022867, 0.92738539, 0.79737861,
        0.20599467]),
 'split2_test_score': array([0.91402762, 0.93001018, 0.95264801, 0.94439464, 0.85274559,
        0.74920172]),
 'split3_test_score': array([ 0.44662358, -0.54487849,  0.31260485,  0.75674824, -0.62942579,
         0.34225889]),
 'split4_test_score': array([0.92894643, 0.80916837, 0.95866138, 0.87123801, 0.8686012 ,
        0.89444242]),
 'mean_test_score': array([0.77739171, 0.52763208, 0.78431104, 0.86712921, 0.54678661,
        0.61206291]),
 'std_test_score': array([0.17562494, 0.55307687, 0.24071256, 0.06749537, 0.58858478,
        0.28353068]),
 'rank_test_score': array([3, 6, 2, 1, 5, 4], dtype=int32)}

In [14]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015122,0.009281,0.016091,0.005150,squared_error,best,"{'criterion': 'squared_error', 'splitter': 'be...",0.832358,0.765002,0.914028,0.446624,0.928946,0.777392,0.175625,3
1,0.014576,0.010043,0.011194,0.003169,squared_error,random,"{'criterion': 'squared_error', 'splitter': 'ra...",0.898731,0.545130,0.930010,-0.544878,0.809168,0.527632,0.553077,6
2,0.007922,0.004630,0.007876,0.004631,absolute_error,best,"{'criterion': 'absolute_error', 'splitter': 'b...",0.857412,0.840229,0.952648,0.312605,0.958661,0.784311,0.240713,2
3,0.006448,0.001464,0.005465,0.001527,absolute_error,random,"{'criterion': 'absolute_error', 'splitter': 'r...",0.835880,0.927385,0.944395,0.756748,0.871238,0.867129,0.067495,1
4,0.005698,0.001165,0.005163,0.000634,poisson,best,"{'criterion': 'poisson', 'splitter': 'best'}",0.844633,0.797379,0.852746,-0.629426,0.868601,0.546787,0.588585,5
5,0.005830,0.001008,0.003639,0.000188,poisson,random,"{'criterion': 'poisson', 'splitter': 'random'}",0.868417,0.205995,0.749202,0.342259,0.894442,0.612063,0.283531,4

In [15]:
y_predict=regressor_grid.predict(x_test)
print(y_predict)
print(y_test)

[101004.64 141585.52 141585.52  78239.91 191792.06 108733.99  71498.49
  99937.59 108733.99 156122.51 108552.04  89949.14 107404.34  89949.14
 134307.35]
       Profit
28  103282.38
11  144259.40
10  146121.95
41   77798.83
2   191050.39
27  105008.31
38   81229.06
31   97483.56
22  110352.25
4   166187.94
33   96778.92
35   96479.51
26  105733.54
34   96712.80
18  124266.90

In [19]:
from sklearn.metrics  import r2_score
r_score=r2_score(y_test,y_predict)
print('The best model',regressor_grid.best_params_)
print('The rscore value',r_score)

The best model {'criterion': 'absolute_error', 'splitter': 'random'}
The rscore value 0.9597490674199076